sudo: false

language: python

services:
  - postgresql
  - elasticsearch

env:
  global:
    - DATABASE_URL='postgres://postgres:@localhost:5432/test_db'
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.test_travis
    - RABBITMQ_HOST = 'rabbitmq'

python:
  - '3.4.5'

addons:
  postgresql: "9.3"
  elasticsearch: "2.4.2"
  apt:
    source:
    - elasticsearch-2.4.2
    packages:
    - postgresql-9.3-postgis-2.3
    - elasticsearch

install:
  - pip install coveralls
  - pip install -r REQUIREMENTS-dev.txt
  - nodeenv -p --node=0.10.31
  - npm -g install yuglify
  - pip install Django==1.8.14

before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db

script:
  # - flake8 --config .flake8 django_project
  - elasticsearch -v
  - curl http://127.0.0.1:9200/
  - cd django_project
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test

after_success:
  - coveralls
